- hosts: all
  user: vagrant
  sudo: yes
  roles:
    - role: btsync
      btsync_user: btsync
      btsync_settings:
        check_for_updates: false
        device_name: "{{ ansible_fqdn }}"
        listening_port : 5999
        pid_file: "{{ btsync_home }}/.sync/btsync.pid"
        storage_path: "{{ btsync_home }}/.sync"
        # webui:
        #   login: "api"
        #   password: "api"
        #   api_key: "YOUR_API_KEY"
        #   listen: "0.0.0.0:8888"
        # shared_folders:
        #   - dir: "{{ btsync_home }}/FOLDER_NAME"
        #     secret: YOUR_SECRET_GOES_HEER
        #     use_relay_server: true
        #     use_tracker: true
        #     use_dht: false
        #     search_lan: true
        #     use_sync_trash: true