---
- name: Create folder for binary
  file: path="{{ btsync_dist }}" recurse=yes
    owner=root group=root mode=0755
    state=directory

- name: Read BTSync version
  shell: >
    {{ btsync_dist }}/btsync --help | awk '/^BitTorrent/ { print $3 }'
  register: btsync_version
  changed_when: false

- debug: msg="BTSync version {{ btsync_version.stdout }}"
  when: btsync_version.stdout

- name: Download btsync tarball
  get_url: >
    url="{{ btsync_url[ansible_architecture] }}"
    dest=/var/tmp/btsync.tgz
  register: tarball_downloaded

- name: Unzip btsync binary
  command: tar xz -f /var/tmp/btsync.tgz btsync
    chdir="{{ btsync_dist }}"
  notify: restart btsync
